language: java
sudo: false
dist: trusty
script: mvn -Psafer -Pintegration -B -e -T 1C verify
jdk: oraclejdk8

env:
  # the SONAR_TOKEN variable
  - secure: "I5+yc30WyUJLIGhajhIFckqSEKDigjqFGovxE3pPsYatPDnFdjqaajEjaI13D0f2QsrC5aBLeFYh3HHnTnv0GIB93gsjVuZdNi8tKMqM1pl6P8N529dE+Ox8/JODvGWr2xSHeL7aLv54FSsO8K+e1lOd332A+a5Xjfsa26b1ob5e5Euc7xr4xTDS9HbXtdQuWODBefQP5bflPBlSOOezP609zfwf+tA87B/zJebvTZ5YzhBWqeA241Gq7mDYznywTvPN61kDMUZjN/lXcK2QPwEv2ENccGHT5AjHVps6Ni1eSgtK3ak/hBrOowiMzJhmtjFWdLoeR6ho5bhVOMN6rUVy4CXPfAMNFZk/NHJxZaAvmriEl+TtpUIDkjiBvKw36s1lnhO3rfzTHXM7uTuPl8hqjdcDkbTcnA9paqmAkui0vMwmFEAk9shx2S1v+5svFiDzUaRkUA6ZktkFaWKudqr+cd2mJZovEGGaVawECIKEcudbnWaVhQtPUUnHe1Sn0gJfkyidebS/rmepopBo1mC6V9WsYNCZ08UDOQLg7hhof7SRERZ4zTLKkv1+RDx81r/g8EHODVVbnNryMM9ShCq2UlUWh6d1IwOvUxxxigNtYBUb+z67KurvFA81ZuzVXFnnmuV6Th0hsMaKVBQC+oQEqSsWuTt70+AKfjAvb2Q="
  # TODO: Add a SONAR_GITHUB_TOKEN to support Sonar on pull requests (or wait until they improve their compatibility)

addons:
  sonarqube:
    branches:
      - devel
      - master
  apt:
    packages:
      - oracle-java8-installer

before_script:
- export GIT_BRANCH=$TRAVIS_BRANCH

cache:
  directories:
    - '$HOME/.sonar/cache'

install:
- mvn dependency:go-offline
  
after_success:
  - if [[ $TRAVIS_REPO_SLUG = 8kdata/mongowp ]]; then bash <(curl -s https://codecov.io/bash) || echo 'Codecov did not collect coverage reports'; else echo 'Codecov not notified'; fi
  - if [[ $TRAVIS_REPO_SLUG = 8kdata/mongowp ]]; then mvn sonar:sonar || echo 'Error while notifying SonarQube'; else echo 'SonarQube not notified'; fi

before_deploy:
  - echo "<settings><servers><server><id>ossrh-snapshot</id><username>\${env.MAVEN_DEPLOY_USER}</username><password>\${env.MAVEN_DEPLOY_PASS}</password></server><server><id>ossrh-release</id><username>\${env.MAVEN_DEPLOY_USER}</username><password>\${env.MAVEN_DEPLOY_PASS}</password></server></servers></settings>" > ~/settings.xml

deploy:
- provider: script
  script: mvn -B -e -T 1C -Pdeploy -DskipTests=true deploy --settings ~/settings.xml
  skip_cleanup: true
  on:
    repo: 8kdata/mongowp
    branch: devel
jdk: oraclejdk8